# Generated by Django 4.0 on 2021-12-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tejas_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=12),
        ),
    ]
