# Generated by Django 4.0 on 2021-12-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tejas_App', '0002_alter_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
