# Generated by Django 4.0 on 2021-12-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tejas_App', '0003_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=20)),
                ('From', models.CharField(max_length=20)),
                ('to', models.CharField(max_length=20)),
            ],
        ),
    ]
